 [theme]
primaryColor = "#198754"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"

[general]
pageTitle = "Гидромодуль – расчёт водоподачи"
favicon = "https://raw.githubusercontent.com/khassen-zhan/hydro_project/main/icon.png"
